from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    PROFESSION_CHOICES = [
        ('entrepreneur', 'Entrepreneur'),
        ('proprietaire', 'Propriétaire'),
        ('investisseur', 'Investisseur'),
        ('locataire', 'Locataire'),
        ('agent_immobilier', 'Agent Immobilier'),
        ('architecte', 'Architecte'),
        ('decorateur', 'Décorateur d\'Intérieur'),
        ('autre', 'Autre'),
    ]
    profession = models.CharField(max_length=20, choices=PROFESSION_CHOICES, blank=True)
    profile_photo = models.ImageField(upload_to='profile_photos/', blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True)

    CITY_CHOICES = [
        ("Abidjan", "Abidjan"),
        ("Yamoussoukro", "Yamoussoukro"),
        ("Bouaké", "Bouaké"),
        ("Daloa", "Daloa"),
        ("San-Pédro", "San-Pédro"),
        ("Korhogo", "Korhogo"),
        ("Gagnoa", "Gagnoa"),
        ("Soubré", "Soubré"),
        ("Man", "Man"),
        ("Anyama", "Anyama"),
        ("Abengourou", "Abengourou"),
        ("Grand-Bassam", "Grand-Bassam"),
        ("Divo", "Divo"),
        ("Agboville", "Agboville"),
        ("Katiola", "Katiola"),
        ("Bondoukou", "Bondoukou"),
        ("Ferkessédougou", "Ferkessédougou"),
        ("Adzopé", "Adzopé"),
        ("Oumé", "Oumé"),
        ("Dabou", "Dabou"),
        ("Sinfra", "Sinfra"),
        ("Bingerville", "Bingerville"),
        ("Duekoué", "Duekoué"),
        ("Dimbokro", "Dimbokro"),
        ("Séguéla", "Séguéla"),
        ("Aboisso", "Aboisso"),
        ("Daoukro", "Daoukro"),
        ("Odienné", "Odienné"),
        ("Bangolo", "Bangolo"),
        ("Biankouma", "Biankouma"),
        ("Sassandra", "Sassandra"),
        ("Bouna", "Bouna"),
        ("Touba", "Touba"),
        ("Zoukougbeu", "Zoukougbeu"),
        ("Bouaflé", "Bouaflé"),
        ("Mankono", "Mankono"),
        ("Kounahiri", "Kounahiri"),
    ]
    city = models.CharField(max_length=100, choices=CITY_CHOICES, blank=True)

    COMMUNE_CHOICES = [
    ("Abengourou", "Abengourou"),
    ("Abobo", "Abobo"),
    ("Aboisso", "Aboisso"),
    ("Adiaké", "Adiaké"),
    ("Adjamé", "Adjamé"),
    ("Agboville", "Agboville"),
    ("Agnibilékrou", "Agnibilékrou"),
    ("Akoupé", "Akoupé"),
    ("Anyama", "Anyama"),
    ("Arrah", "Arrah"),
    ("Assuéfry", "Assuéfry"),
    ("Attécoubé", "Attécoubé"),
    ("Ayémé", "Ayémé"),
    ("Azaguié", "Azaguié"),
    ("Bako", "Bako"),
    ("Bangolo", "Bangolo"),
    ("Bassawa", "Bassawa"),
    ("Bédiala", "Bédiala"),
    ("Béoumi", "Béoumi"),
    ("Bettié", "Bettié"),
    ("Biankouma", "Biankouma"),
    ("Bingerville", "Bingerville"),
    ("Bin-Houyé", "Bin-Houyé"),
    ("Bloléquin", "Bloléquin"),
    ("Bocanda", "Bocanda"),
    ("Bodokro", "Bodokro"),
    ("Bondoukou", "Bondoukou"),
    ("Bongouanou", "Bongouanou"),
    ("Bonon", "Bonon"),
    ("Bonoua", "Bonoua"),
    ("Booko", "Booko"),
    ("Bouaflé", "Bouaflé"),
    ("Bouaké", "Bouaké"),
    ("Bouna", "Bouna"),
    ("Boundiali", "Boundiali"),
    ("Brobo", "Brobo"),
    ("Buyo", "Buyo"),
    ("Cocody", "Cocody"),
    ("Dabakala", "Dabakala"),
    ("Dabou", "Dabou"),
    ("Daloa", "Daloa"),
    ("Daoukro", "Daoukro"),
    ("Dianra", "Dianra"),
    ("Didiévi", "Didiévi"),
    ("Dimbokro", "Dimbokro"),
    ("Divo", "Divo"),
    ("Djékanou", "Djékanou"),
    ("Djibrosso", "Djibrosso"),
    ("Ferkessédougou", "Ferkessédougou"),
    ("Fresco", "Fresco"),
    ("Grand-Bassam", "Grand-Bassam"),
    ("Guéyo", "Guéyo"),
    ("Guibéroua", "Guibéroua"),
    ("Guiglo", "Guiglo"),
    ("Issia", "Issia"),
    ("Jacqueville", "Jacqueville"),
    ("Kaniasso", "Kaniasso"),
    ("Katiola", "Katiola"),
    ("Kokumbo", "Kokumbo"),
    ("Korhogo", "Korhogo"),
    ("Koumassi", "Koumassi"),
    ("Koumbala", "Koumbala"),
    ("Kouassi-Datékro", "Kouassi-Datékro"),
    ("Kouassi-Kouassikro", "Kouassi-Kouassikro"),
    ("Kouibly", "Kouibly"),
    ("Kouto", "Kouto"),
    ("Lakota", "Lakota"),
    ("Logoualé", "Logoualé"),
    ("Madina-N'Gana", "Madina-N'Gana"),
    ("Man", "Man"),
    ("Mankono", "Mankono"),
    ("Massala", "Massala"),
    ("Mayo", "Mayo"),
    ("M'Bahiakro", "M'Bahiakro"),
    ("M'Batto", "M'Batto"),
    ("Méagui", "Méagui"),
    ("Minignan", "Minignan"),
    ("Morondo", "Morondo"),
    ("Napiéolédougou", "Napiéolédougou"),
    ("Nassian", "Nassian"),
    ("N'Djébonouan", "N'Djébonouan"),
    ("Niablé", "Niablé"),
    ("Niakaramandougou", "Niakaramandougou"),
    ("Niellé", "Niellé"),
    ("Niofoin", "Niofoin"),
    ("Odienné", "Odienné"),
    ("Ouaninou", "Ouaninou"),
    ("Ouellé", "Ouellé"),
    ("Oumé", "Oumé"),
    ("Ouragahio", "Ouragahio"),
    ("Plateau", "Plateau"),
    ("Port-Bouët", "Port-Bouët"),
    ("Prikro", "Prikro"),
    ("Rubino", "Rubino"),
    ("Saïoua", "Saïoua"),
    ("Sakassou", "Sakassou"),
    ("San-Pédro", "San-Pédro"),
    ("Sassandra", "Sassandra"),
    ("Séguéla", "Séguéla"),
    ("Sikensi", "Sikensi"),
    ("Sinématiali", "Sinématiali"),
    ("Sinfra", "Sinfra"),
    ("Sipilou", "Sipilou"),
    ("Sirasso", "Sirasso"),
    ("Songon", "Songon"),
    ("Soubré", "Soubré"),
    ("Taabo", "Taabo"),
    ("Tabou", "Tabou"),
    ("Tafiré", "Tafiré"),
    ("Tanda", "Tanda"),
    ("Téhini", "Téhini"),
    ("Tiapoum", "Tiapoum"),
    ("Tiassalé", "Tiassalé"),
    ("Tiébissou", "Tiébissou"),
    ("Tiémélékro", "Tiémélékro"),
    ("Tié-N'Diékro", "Tié-N'Diékro"),
    ("Tienko", "Tienko"),
    ("Tioroniaradougou", "Tioroniaradougou"),
    ("Touba", "Touba"),
    ("Toulépleu", "Toulépleu"),
    ("Toumodi", "Toumodi"),
    ("Transua", "Transua"),
    ("Treichville", "Treichville"),
]
    commune = models.CharField(max_length=100, choices=COMMUNE_CHOICES, blank=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

